### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by vjnrv** [crossjoin/PreMailer#1]
Hi, thank you for this library.

I tried to install with composer, but got the following problem:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crossjoin/pre-mailer dev-master -> satisfiable by crossjoin/pre-mailer[dev-master].
    - crossjoin/pre-mailer dev-master requires crossjoin/css 1.0.*@dev -> no matching package found.
```

Create a tag should resolve this problem... i think.

**Comment by crossjoin** [comment]
Hello, and thanks a lot for the info. I tried to use branch aliases, but this doesn't seem to work. Also I had a problem with the version of the symfony component I use, so I switched to the last stable one.

Everything should work now.

**Comment by jtrolle** [comment]
thanks! :+1:
