### ISSUE TITLE
Validation of the option for text line width is incorrect

### ISSUE THREAD

**Issue by bramley** [crossjoin/PreMailer#2]
The test for the value of text line width option is the wrong way around at https://github.com/crossjoin/PreMailer/blob/master/src/Crossjoin/PreMailer/PreMailerAbstract.php#L135

    if ($value >= 0) {
It should be 

    if ($value <= 0) {

**Comment by crossjoin** [comment]
Thank you. I fixed the bug and will create a new release soon.
